swagger: '2.0'
info:
  version: 1.0.0
  title: Testify REST API
  description: API for interacting with testify test results
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /testresults:
    get:
      description: Returns all test results from the automation pipeline.
      operationId: findTests
      produces:
        - application/json
        - application/xml
        - text/xml
        - text/html
      responses:
        '200':
          description: getTestResult response
          schema:
            type: array
            items:
              $ref: '#/definitions/testresult'
    post:
      description: Creates a new test result.
      operationId: addTest
      produces:
        - application/json
      parameters:
        - name: testresult
          in: body
          description: Test to add
          required: true
          schema:
            $ref: '#/definitions/newtestresult'
      responses:
        '200':
          description: test result response
          schema:
            $ref: '#/definitions/testresult'
  '/testresults/{id}':
    get:
      description: Returns a test result based on a single ID.
      operationId: findTestById
      produces:
        - application/json
        - application/xml
        - text/xml
        - text/html
      parameters:
        - name: id
          in: path
          description: ID of test to fetch
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: test results response
          schema:
            $ref: '#/definitions/testresult'
    delete:
      description: deletes a single test based on the ID supplied
      operationId: deleteTest
      parameters:
        - name: id
          in: path
          description: ID of test to delete
          required: true
          type: integer
          format: int64
      responses:
        '204':
          description: test deleted
definitions:
  testresult:
    type: object
    required:
      - id
    properties:
        operation:
          type: string
        id:
          type: integer
          format: int64
        date:
          type: string
        harness:
          type: string
        passpercentage:
          type: integer
  newtestresult:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
        format: int64
      date:
        type: string
      harness:
        type: string
      passpercentage:
        type: integer
